### ISSUE TITLE
TypeError: t.getCurrentLocation is not a function

### ISSUE THREAD

**Issue by gardner** [guillaumeparis2000/react-piwik#12]
When using with React Router v4 I receive the error:

`TypeError: t.getCurrentLocation is not a function`

```
import { Router } from 'react-router-dom'
import ReactPiwik from 'react-piwik'
...
ReactDOM.render((
  <ApolloProvider store={store} client={client}>
    <Router history={piwik.connectToHistory(history)}>
      <App />
    </Router>
  </ApolloProvider>
), document.getElementById('root'))
```

**Comment by gardner** [comment]
Looks like it's happening here: https://github.com/guillaumeparis2000/react-piwik/blob/master/src/React-Piwik.js#L59

**Comment by gardner** [comment]
Looks like they removed the method in 4.0.x: https://github.com/ReactTraining/history/compare/v4.0.0-1...v4.0.0-2#diff-8b1c3fd0d4a6765c16dfd18509182f9dR5

**Comment by gardner** [comment]
Here's a PR to work around breaking changes in `history`: https://github.com/guillaumeparis2000/react-piwik/pull/13

**Comment by guillaumeparis2000** [comment]
Thanks for the fix, I just went to publish it on the version 1.3.0
