### ISSUE TITLE
@types/react-piwik

### ISSUE THREAD

**Issue by cafca** [guillaumeparis2000/react-piwik#29]
Does anybody plan to publish Typescript types for this library? Might be interested in helping here.

**Comment by guillaumeparis2000** [comment]
It's a good idea but I haven't got a lot of time to do it for the moment. Feel free to open a PR.
Thanks

**Comment by evelynhathaway** [comment]
@guillaumeparis2000 I opened a PR for it. @cafca, maybe you could help by adding your review. 😄

**Comment by cafca** [comment]
@evelynhathaway so cool! I wasn't quick enough here. Thank you for this.
