### ISSUE TITLE
Add support for history v5 and react-router-dom v6

### ISSUE THREAD

**Issue by evelynhathaway** [guillaumeparis2000/react-piwik#32]
- [ ] Create a branch for the call signature for the `history.listen()` callback in `history` v5 and `react-router-dom` v6
- [ ] Add `History5` type for the new call signature and test types

_Originally referenced by @evelynhathaway in https://github.com/guillaumeparis2000/react-piwik/pull/31#discussion_r487456860_

**Comment by guillaumeparis2000** [comment]
Thanks for the fix, published in version v1.9.0

**Comment by evelynhathaway** [comment]
I didn't fix the compatibility issue in the typings MR. I left this open as future work. It should be an easy issue to take on for someone during Hacktoberfest. ☺️
