### ISSUE TITLE
Initial page view is not tracked 

### ISSUE THREAD

**Issue by totutotu** [guillaumeparis2000/react-piwik#35]
When first entering a site the first page view is not being tracked. 

This issue was fixed a long time ago in [this commit](https://github.com/guillaumeparis2000/react-piwik/pull/3/commits/4fd7d7038b5ebaffcd740b2504595c8ca9135361) but the fix has since been removed.

When initiating to use of react-piwik by using the "connectToHistory" function the previousPath local variable is set to current page the user is on [here](https://github.com/guillaumeparis2000/react-piwik/blob/51deb4971344cb0c5f7b6a4644ec0781ccac1654/src/React-Piwik.js#L72). Because the "previousPath" variable is in fact the same location that the user is currently on, the listening track() function [does not recognize the first page as a trackable visit](https://github.com/guillaumeparis2000/react-piwik/blob/51deb4971344cb0c5f7b6a4644ec0781ccac1654/src/React-Piwik.js#L104).

Edit: Update: Seems history.listen does not trigget the first trigger of the track function, so a solution would be to manually trigger the track function on "connectToHistory" with the initial location.

**Comment by guillaumeparis2000** [comment]
Thanks for the fix, I publish it in version v1.10.0.
